---
title: "Exploratory Data Analysis"
output: github_document
date: "2025-10-02"
---
```{r}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


Import Weather Data
```{r}
data("weather_df")


weather_df = 
  weather_df |> 
  mutate(month = floor_date(date, unit = "month")) 


#floor(date() --> this takes the date and makes it a month. Ex.Feb 21st becomes Feb 1st 
#Look into package lubridate --> all about how to work with dates
```

Make plots

```{r}

weather_df |> 
  ggplot(aes(x=prcp)) +
  geom_histogram()

#right off the bat we can see some extreme values.
```

First thing, check extreme values

```{r}
weather_df |> 
  filter(prcp >1000)
```


Look at data again

```{r}
weather_df |> 
  filter(tmax >= 20, tmax <= 30) |> 
  ggplot(aes( x = tmin, y = tmax, color = name)) +
  geom_point()

#check out why waterhole is looking different than Malakai and NYC? It is because of how they got their temp.
```

Group by name
```{r}
weather_df |> 
  group_by(name)
#gives three distinct groups

weather_df |> 
  group_by(name, month)
#gives 72 becuase 12 months and 3 groups 
```


Sumarize groups 

```{r}
weather_df |> 
  group_by(name) |> 
  summarize(
    n = n()
  )

#prints out tibble



weather_df |> 
  group_by(name, month) |> 
  summarize(
    n = n()
  )
#n tells us how many days are in each month here


#distinct instances
weather_df |> 
  group_by(month) |> 
  summarise(
    n = n_distinct(date)
  )
```


Special function to count directly

```{r}
weather_df |> 
  count(name) #short hand that says group by name and count by group
```


```{r}
weather_df |> 
  group_by(name, month) |> 
  summarise(
    mean_tmax = mean(tmax, na.rm = TRUE),
    median_tmin = median(tmin, na.rm = TRUE),
    sd_prcp = sd(prcp, na.rm = TRUE)
  ) |> view()

```

This is still a dataframe

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarise(
    mean_tmax = mean(tmax, na.rm = TRUE)
    ) |> 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_line()
  
  
```

Sometimes you need to format results more nicely

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarise(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) |> 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) |> 
  knitr::kable(digits = 2)
```

